// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApXcmKVAcqvTLq0_Lj_IZmYhgdk9Dpwzs',
    appId: '1:32079840668:web:9799c06dc0bc609dc33459',
    messagingSenderId: '32079840668',
    projectId: 'freshcart-2fae2',
    authDomain: 'freshcart-2fae2.firebaseapp.com',
    storageBucket: 'freshcart-2fae2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaTyh-cQyfWCRsp5Ipq2Y8TeL8uPbJwmI',
    appId: '1:32079840668:android:a061cb981d48af8fc33459',
    messagingSenderId: '32079840668',
    projectId: 'freshcart-2fae2',
    storageBucket: 'freshcart-2fae2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQpCPkVme7aYyS9ydztMQKeJcQg7qhWo8',
    appId: '1:32079840668:ios:cf942017f577cdd1c33459',
    messagingSenderId: '32079840668',
    projectId: 'freshcart-2fae2',
    storageBucket: 'freshcart-2fae2.appspot.com',
    iosBundleId: 'com.example.freshcart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQpCPkVme7aYyS9ydztMQKeJcQg7qhWo8',
    appId: '1:32079840668:ios:8f4d7eac47eda97dc33459',
    messagingSenderId: '32079840668',
    projectId: 'freshcart-2fae2',
    storageBucket: 'freshcart-2fae2.appspot.com',
    iosBundleId: 'com.example.freshcart.RunnerTests',
  );
}
